jobs:
- job: 'cppWindows'  
  pool:
    vmImage: windows-2019    
  displayName: 'C++ (Windows)'

  strategy:
    maxParallel: 2
    matrix:
      x64-Release:
        buildPlatform: 'x64'
        buildConfiguration: 'Release'
  
  steps:
  - checkout: self
    submodules: recursive
  - task: CMake@1
    displayName: 'CMake .. -G "Visual Studio 16 2019"'
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '.. -G "Visual Studio 16 2019"'

  - task: MSBuild@1
    displayName: 'Build solution build/FishStore.sln'
    inputs:
      solution: 'build/FishStore.sln'
      msbuildArguments: '/m /p:Configuration=$(buildConfiguration) /p:Platform=$(buildPlatform)'

  - task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- job: 'cppLinux'
  pool:
    vmImage: ubuntu-16.04
  displayName: 'C++ (Linux)'
  
  steps:
  - checkout: self
    submodules: recursive
  - script: |
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt update
      sudo apt install -y g++-7 libaio-dev uuid-dev libtbb-dev
    displayName: 'Install depdendencies'
  
  - script: |
      export CXX='g++-7'
      mkdir -p build/Release
      cd build/Release
      cmake -DCMAKE_BUILD_TYPE=Release ../..
      make -j
      ./in_memory_test
      ./ingest_queue_test
      ./register_test
      ./checkpoint_queue_test
    displayName: 'Compile and Test'
